[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

[[redirects]]
  from = "https://thebolderbrew.com/recommends/fellow-stagg-ekg"
  to = "https://fellowproducts.com/products/staggekg?rfsn=4717192.b9efad&utm_source=refersion&utm_medium=affiliate&utm_campaign=4717192.b9efad"
